version: '2'
services:
    jupyter:
        container_name: jupyter_notebook   
        image: jupyter/base-notebook:latest            
        ports:
            - 8888:8888
        command: start-notebook.sh --NotebookApp.token=''
